var searchData=
[
  ['serial_20peripheral_20interface_20_28dspi_29',['Serial Peripheral Interface (DSPI)',['../group__dspi.html',1,'']]],
  ['signed_20integer_20operands',['Signed Integer Operands',['../group__int__instructions.html',1,'']]],
  ['synchronous_20audio_20interface_20_28sai_29',['Synchronous Audio Interface (SAI)',['../group__sai.html',1,'']]],
  ['sai_20peripheral_20driver',['SAI Peripheral driver',['../group__sai__driver.html',1,'']]],
  ['sai_20hal_20driver',['SAI HAL driver',['../group__sai__hal.html',1,'']]],
  ['system_20clock_20generator_20_28scg_29',['System Clock Generator (SCG)',['../group__scg.html',1,'']]],
  ['scg_20hal_20driver',['SCG HAL driver',['../group__scg__hal.html',1,'']]],
  ['secured_20digital_20host_20controller_20_28sdhc_29',['Secured Digital Host Controller (SDHC)',['../group__sdhc.html',1,'']]],
  ['sdhc_20card_20related_20standard_20definition',['SDHC Card Related Standard Definition',['../group__sdhc__card__std__def.html',1,'']]],
  ['sdhc_20card_20driver',['SDHC Card Driver',['../group__sdhc__carddrv.html',1,'']]],
  ['sdhc_20card_20definition',['SDHC Card Definition',['../group__sdhc__carddrv__data__types.html',1,'']]],
  ['sdhc_20hal',['SDHC HAL',['../group__sdhc__hal.html',1,'']]],
  ['sdhc_20peripheral_20driver',['SDHC Peripheral Driver',['../group__sdhc__pd.html',1,'']]],
  ['sdhc_20data_20types',['SDHC Data Types',['../group__sdhc__pd__data__types.html',1,'']]],
  ['sdhc_20standard_20definition',['SDHC Standard Definition',['../group__sdhc__std__def.html',1,'']]],
  ['synchronous_20dram_20controller_20_28sdram_29',['Synchronous DRAM Controller (SDRAM)',['../group__sdramc.html',1,'']]],
  ['sdramc_20peripheral_20driver',['SDRAMC Peripheral driver',['../group__sdramc__driver.html',1,'']]],
  ['sdramc_20hal_20driver',['SDRAMC HAL driver',['../group__sdramc__hal.html',1,'']]],
  ['sd_20card_20spi_20driver',['SD Card SPI Driver',['../group__sdspi__carddrv.html',1,'']]],
  ['sd_20card_20spi_20data_20definition',['SD Card SPI Data Definition',['../group__sdspi__carddrv__data__types.html',1,'']]],
  ['system_20integration_20module_20_28sim_29',['System Integration Module (SIM)',['../group__sim.html',1,'']]],
  ['sim_20hal_20driver',['SIM HAL driver',['../group__sim__hal.html',1,'']]],
  ['slcd_20peripheral_20driver',['SLCD Peripheral driver',['../group__slcd__driver.html',1,'']]],
  ['slcd_20hal_20driver',['SLCD HAL driver',['../group__slcd__hal.html',1,'']]],
  ['smart_20card',['Smart Card',['../group__smartcard.html',1,'']]],
  ['smart_20card_20driver',['Smart Card driver',['../group__smartcard__driver.html',1,'']]],
  ['smart_20card_20emvsim_20driver',['Smart Card EMVSIM Driver',['../group__smartcard__emvsim__driver.html',1,'']]],
  ['smart_20card_20interface_20direct_20driver',['Smart Card Interface Direct Driver',['../group__smartcard__interface__direct.html',1,'']]],
  ['smart_20card_20interface_20driver',['Smart Card Interface Driver',['../group__smartcard__interface__driver.html',1,'']]],
  ['smart_20card_20interface_20ncn8025_20driver',['Smart Card Interface NCN8025 Driver',['../group__smartcard__interface__ncn8025.html',1,'']]],
  ['smart_20card_20uart_20driver',['Smart Card UART Driver',['../group__smartcard__uart__driver.html',1,'']]],
  ['system_20mode_20controller_20_28smc_29',['System Mode Controller (SMC)',['../group__smc.html',1,'']]],
  ['smc_20hal_20driver',['SMC HAL driver',['../group__smc__hal.html',1,'']]],
  ['serial_20peripheral_20interface_20_28spi_29',['Serial Peripheral Interface (SPI)',['../group__spi.html',1,'']]],
  ['spi_20classes',['SPI Classes',['../group__spi__classes.html',1,'']]],
  ['spi_20master_20peripheral_20driver',['SPI Master Peripheral Driver',['../group__SPI__DRV__MasterDriver.html',1,'']]],
  ['spi_20hal_20driver',['SPI HAL driver',['../group__spi__hal.html',1,'']]],
  ['spi_20slave_20peripheral_20driver',['SPI Slave Peripheral Driver',['../group__spi__slave__driver.html',1,'']]],
  ['shared_20spi_20types',['Shared SPI Types',['../group__spi__types.html',1,'']]]
];
