var searchData=
[
  ['low_2dleakage_20wakeup_20unit_20_28llwu_29',['Low-Leakage Wakeup Unit (LLWU)',['../group__llwu__hal.html',1,'']]],
  ['local_20memory_20controller_20_28lmem_29_20cache_20control_20driver',['Local Memory Controller (LMEM) Cache Control Driver',['../group__lmem.html',1,'']]],
  ['lmem_20cache_20driver',['LMEM Cache Driver',['../group__local__memory__controller__cache__driver.html',1,'']]],
  ['lmem_20cache_20hal_20driver',['LMEM Cache HAL driver',['../group__local__memory__controller__cache__hal.html',1,'']]],
  ['lp_20inter_2dintegrated_20circuit_20_28lpi2c_29',['LP Inter-Integrated Circuit (LPI2C)',['../group__lpi2c.html',1,'']]],
  ['lpi2c_20hal_20driver',['LPI2C HAL driver',['../group__lpi2c__hal.html',1,'']]],
  ['lpi2c_20master_20peripheral',['LPI2C Master peripheral',['../group__lpi2c__master.html',1,'']]],
  ['lpi2c_20slave_20peripheral_20driver',['LPI2C Slave peripheral driver',['../group__lpi2c__slave.html',1,'']]],
  ['lpsci_20peripheral_20driver',['LPSCI Peripheral driver',['../group__lpsci__driver.html',1,'']]],
  ['lpsci_20hal_20driver',['LPSCI HAL driver',['../group__lpsci__hal.html',1,'']]],
  ['low_20power_20timer_20_28lptmr_29',['Low Power Timer (LPTMR)',['../group__lptmr.html',1,'']]],
  ['lptmr_20peripheral_20driver',['LPTMR Peripheral driver',['../group__lptmr__driver.html',1,'']]],
  ['lptmr_20hal_20driver',['LPTMR HAL driver',['../group__lptmr__hal.html',1,'']]],
  ['low_20power_20universal_20asynchronous_20receiver_2ftransmitter_20_28lpuart_29',['Low Power Universal Asynchronous Receiver/Transmitter (LPUART)',['../group__lpuart.html',1,'']]],
  ['lpuart_20peripheral_20driver',['LPUART Peripheral driver',['../group__lpuart__driver.html',1,'']]],
  ['lpuart_20hal_20driver',['LPUART HAL driver',['../group__lpuart__hal.html',1,'']]],
  ['lpuart_20type_20definitions',['LPUART Type Definitions',['../group__lpuart__types.html',1,'']]],
  ['lp_20trusted_20cryptography_20_28ltc_29',['LP Trusted Cryptography (LTC)',['../group__ltc.html',1,'']]],
  ['ltc_20driver',['LTC driver',['../group__ltc__driver.html',1,'']]],
  ['ltc_20aes_20driver',['LTC AES driver',['../group__ltc__driver__aes.html',1,'']]],
  ['ltc_20des_20driver',['LTC DES driver',['../group__ltc__driver__des.html',1,'']]],
  ['ltc_20hash_20driver',['LTC HASH driver',['../group__ltc__driver__hash.html',1,'']]],
  ['ltc_20pkha_20driver',['LTC PKHA driver',['../group__ltc__driver__pkha.html',1,'']]],
  ['ltc_20hal_20driver',['LTC HAL driver',['../group__ltc__hal.html',1,'']]],
  ['lcd_20_28slcd_29',['LCD (SLCD)',['../group__segment.html',1,'']]]
];
