var modules =
[
    [ "12-bit Cyclic Analog-to-Digital Converter (CADC)", "group__cadc.html", "group__cadc" ],
    [ "16-bit SAR Analog-to-Digital Converter (ADC16)", "group__adc16.html", "group__adc16" ],
    [ "Analog Front End (AFE)", "group__afe.html", "group__afe" ],
    [ "C90TFS Flash Driver", "group__c90tfs__flash__driver.html", "group__c90tfs__flash__driver" ],
    [ "Carrier Modulator Transmitter (CMT)", "group__cmt.html", "group__cmt" ],
    [ "Clock Manager (Clock)", "group__clock__manager.html", "group__clock__manager" ],
    [ "Comparator (CMP)", "group__cmp.html", "group__cmp" ],
    [ "Computer Operating Properly (COP) Watchdog Timer", "group__cop.html", "group__cop" ],
    [ "Controller Area Network (FlexCAN)", "group__flexcan.html", "group__flexcan" ],
    [ "Crossbar AND/OR/INVERT (AOI) Module", "group__aoi.html", "group__aoi" ],
    [ "Cyclic Redundancy Check (CRC)", "group__crc.html", "group__crc" ],
    [ "Digital-to-Analog Converter (DAC)", "group__dac.html", "group__dac" ],
    [ "Direct Memory Access  (DMA)", "group__dma.html", "group__dma" ],
    [ "Enhanced Direct Memory Access (eDMA)", "group__edma.html", "group__edma" ],
    [ "Ethernet MAC (ENET)", "group__enet.html", "group__enet" ],
    [ "External Bus Interface (FLEXBUS)", "group__flexbus.html", "group__flexbus" ],
    [ "External Watchdog Timer (EWM)", "group__ewm.html", "group__ewm" ],
    [ "FlexIO (FLEXIO)", "group__flexio.html", "group__flexio" ],
    [ "FlexIO-simulated Camera(FlexIO_Camera)", "group__flexio__camera.html", "group__flexio__camera" ],
    [ "FlexIO-simulated I2C (FlexIO_I2C)", "group__flexio__i2c.html", "group__flexio__i2c" ],
    [ "FlexIO-simulated I2S (FlexIO_I2S)", "group__flexio__i2s.html", "group__flexio__i2s" ],
    [ "FlexIO-simulated SPI (FlexIO_SPI)", "group__flexio__spi.html", "group__flexio__spi" ],
    [ "FlexIO-simulated UART (FlexIO_UART)", "group__flexio__uart.html", "group__flexio__uart" ],
    [ "FlexTimer (FTM)", "group__ftm.html", "group__ftm" ],
    [ "General Purpose Input/Output (GPIO)", "group__gpio.html", "group__gpio" ],
    [ "Hardware Timer Manager Driver", "group__hwtimer__driver.html", "group__hwtimer__driver" ],
    [ "Independent Real Time Clock (IRTC)", "group__irtc.html", "group__irtc" ],
    [ "Inter-Integrated Circuit (I2C)", "group__i2c.html", "group__i2c" ],
    [ "Inter-Peripheral Crossbar Switch (XBAR)", "group__xbar.html", "group__xbar" ],
    [ "Interrupt Manager (Interrupt)", "group__interrupt__manager.html", "group__interrupt__manager" ],
    [ "LCD (SLCD)", "group__segment.html", "group__segment" ],
    [ "LP Inter-Integrated Circuit (LPI2C)", "group__lpi2c.html", "group__lpi2c" ],
    [ "LP Trusted Cryptography (LTC)", "group__ltc.html", "group__ltc" ],
    [ "Local Memory Controller (LMEM) Cache Control Driver", "group__lmem.html", "group__lmem" ],
    [ "Low Power Timer (LPTMR)", "group__lptmr.html", "group__lptmr" ],
    [ "Low Power Universal Asynchronous Receiver/Transmitter (LPUART)", "group__lpuart.html", "group__lpuart" ],
    [ "Low-Leakage Wakeup Unit (LLWU)", "group__llwu__hal.html", "group__llwu__hal" ],
    [ "Memory Mapped Arithmetic Unit (MMAU)", "group__mmau.html", "group__mmau" ],
    [ "Memory Protection Unit (MPU)", "group__mpu.html", "group__mpu" ],
    [ "Memory-Mapped Cryptographic Acceleration Unit (MMCAU)", "group__mmcau.html", "group__mmcau" ],
    [ "Memory-Mapped Divide and Square Root(MMDVSQ)", "group__mmdvsq.html", "group__mmdvsq" ],
    [ "Multipurpose Clock Generator (MCG)", "group__mcg.html", "group__mcg" ],
    [ "Multipurpose Clock Generator Lite (MCG_Lite)", "group__mcglite.html", "group__mcglite" ],
    [ "OS Abstraction Layer (OSA)", "group__os__abstraction.html", "group__os__abstraction" ],
    [ "Oscillator (OSC)", "group__osc.html", "group__osc" ],
    [ "PCC", "group__pcc.html", "group__pcc" ],
    [ "Periodic Interrupt Timer (PIT)", "group__pit.html", "group__pit" ],
    [ "Port Control and Interrupts (PORT)", "group__port.html", "group__port" ],
    [ "Power Management Controller (PMC)", "group__pmc.html", "group__pmc" ],
    [ "Power Manager (Power)", "group__power__manager.html", "group__power__manager" ],
    [ "Programmable Delay Block (PDB)", "group__pdb.html", "group__pdb" ],
    [ "Pulse Width Modulator A (PWMA/eFlexPWM)", "group__pwm.html", "group__pwm" ],
    [ "Quad Serial Peripheral Interface (QSPI)", "group__qspi.html", "group__qspi" ],
    [ "Quad Timer", "group__quadtmr.html", "group__quadtmr" ],
    [ "Quadrature Encoder/Decoder (ENC)", "group__enc.html", "group__enc" ],
    [ "Random Number Generator Accelerator (RNGA)", "group__rnga.html", "group__rnga" ],
    [ "Real Time Clock (RTC)", "group__rtc.html", "group__rtc" ],
    [ "Reference (VREF)", "group__Voltage.html", "group__Voltage" ],
    [ "Reset Control Module (RCM)", "group__rcm.html", "group__rcm" ],
    [ "Secured Digital Host Controller (SDHC)", "group__sdhc.html", "group__sdhc" ],
    [ "Serial Peripheral Interface (DSPI)", "group__dspi.html", "group__dspi" ],
    [ "Serial Peripheral Interface (SPI)", "group__spi.html", "group__spi" ],
    [ "Smart Card", "group__smartcard.html", "group__smartcard" ],
    [ "Synchronous Audio Interface (SAI)", "group__sai.html", "group__sai" ],
    [ "Synchronous DRAM Controller (SDRAM)", "group__sdramc.html", "group__sdramc" ],
    [ "System Clock Generator (SCG)", "group__scg.html", "group__scg" ],
    [ "System Integration Module (SIM)", "group__sim.html", "group__sim" ],
    [ "System Mode Controller (SMC)", "group__smc.html", "group__smc" ],
    [ "Timer/PWM Module (TPM)", "group__tpm.html", "group__tpm" ],
    [ "Touch Sense Input (TSI)", "group__tsi.html", "group__tsi" ],
    [ "True Random Number Generator (TRNG)", "group__trng.html", "group__trng" ],
    [ "Universal Asynchronous Receiver/Transmitter (LPSCI)", "group__lpsci.html", "group__lpsci" ],
    [ "Universal Asynchronous Receiver/Transmitter (UART)", "group__uart.html", "group__uart" ],
    [ "Utilities for the Kinetis SDK", "group__debug__console.html", null ],
    [ "Watchdog Timer (WDOG)", "group__wdog.html", "group__wdog" ]
];